ARG VERSION
ARG BASE_IMAGE
FROM nexus.gillouche.homelab/docker-hub/golang:${VERSION}-trixie AS builder
COPY hello.go /tmp/hello.go
RUN CGO_ENABLED=0 go build -o /tmp/hello /tmp/hello.go

FROM ${BASE_IMAGE}
COPY --from=builder /tmp/hello /tmp/hello
ENTRYPOINT ["/tmp/hello"]
